Class {
	#name : 'SGRessources',
	#superclass : 'Object',
	#classInstVars : [
		'lastGame'
	],
	#category : 'Myg-SameGame-Model',
	#package : 'Myg-SameGame',
	#tag : 'Model'
}

{ #category : 'as yet unclassified' }
SGRessources class >> lastGame [

	<SGLevel: 0>
	^ lastGame
]

{ #category : 'as yet unclassified' }
SGRessources class >> lastGame: aString [

	lastGame := aString
]

{ #category : 'as yet unclassified' }
SGRessources class >> level1 [

	<SGLevel: 1>
	^ '|Y|G|Y|B|Bo|Bo|G|Y|Mu|B|R|B|Y|Mu|B|B|G|R|B|B|
|B|R|Y|Bo|R|Y|G|B|Y|R|G|R|G|B|G|R|G|B|G|R|
|G|G|R|B|R|Y|B|G|B|Y|B|G|R|R|Y|R|G|G|G|R|
|B|B|Y|R|B|G|B|B|R|Lk|B|B|G|G|Y|B|G|Y|Lk|G|
|G|B|Y|Y|Y|Y|R|B|G|Y|Y|G|B|R|G|Y|G|Y|B|B|
|Y|Y|Lk|Y|G|G|B|G|R|R|Y|Lk|G|Y|B|B|G|R|R|R|
|R|Bo|B|B|B|R|R|R|G|B|Bo|Y|G|B|Y|G|Y|B|Cr|B|
|Y|B|G|G|Y|B|Cr|Bo|B|R|R|G|B|R|G|Y|G|B|B|B|
|G|R|G|B|Y|B|R|Bo|Y|R|Lk|B|G|Y|R|R|G|R|B|Y|
|R|Y|Y|Y|G|R|G|Y|G|B|Y|B|G|Y|B|B|Y|R|R|G|
|G|Y|R|B|R|Y|Y|R|Y|Y|Bo|R|G|G|Y|R|G|B|B|R|
|Lk|B|B|R|B|G|R|Y|Y|B|Lk|Y|Y|G|B|B|G|Bo|B|R|
|B|B|B|Y|R|Y|Y|Mu|G|B|G|B|B|B|B|G|B|G|R|G|
|R|G|Y|Mu|G|G|Y|B|Y|B|R|B|R|R|B|Y|R|G|Y|B|
|R|R|B|G|G|B|Y|Y|G|Lk|B|Lk|Y|R|G|G|R|Cr|R|G|
|G|G|G|R|B|G|G|G|B|B|G|B|B|R|R|B|Y|R|G|Y|
|G|G|Y|R|B|G|G|Lk|B|Y|R|R|Y|Mu|R|B|B|Y|R|Cr|
|G|G|Y|R|Y|Y|G|B|R|B|B|G|G|Bo|G|R|G|Y|R|Y|
|G|G|G|Y|G|Mu|B|Y|Y|Y|G|Lk|G|Y|Y|G|G|Y|R|B|
|B|Y|Y|G|B|Mu|B|G|B|R|B|Y|Y|Y|Y|R|R|G|G|Mu|'
]

{ #category : 'as yet unclassified' }
SGRessources class >> level2 [

	<SGLevel: 2>
	^ '|G|Cr|Y|G|B|Lk|Bo|G|B|B|Mu|G|B|G|B|R|G|G|Y|Y|
|R|R|R|G|Y|Y|R|Lk|B|G|B|Y|G|Y|Y|Mu|Y|Y|B|Y|
|R|Y|R|Y|G|G|Y|Y|Y|G|B|G|B|G|Y|G|R|B|Lk|B|
|R|R|G|B|Y|B|Bo|G|Y|G|G|B|Y|G|G|G|G|Y|B|R|
|B|R|B|Y|G|R|R|Cr|Y|Y|Y|Y|G|R|R|Bo|B|B|R|G|
|G|G|R|R|B|G|R|G|R|Y|R|R|R|R|G|Y|B|Bo|B|G|
|Y|R|Y|R|R|R|B|Mu|G|Y|G|G|R|Y|B|Lk|Mu|Y|B|Cr|
|Y|B|B|B|B|R|B|B|B|R|G|Y|G|B|R|Y|R|Y|R|Cr|
|R|G|Y|G|Cr|R|Mu|R|R|Bo|Y|G|Y|G|B|G|Mu|Mu|B|B|
|G|Y|B|G|Y|R|Cr|R|G|R|B|G|Y|G|B|Mu|G|B|R|G|
|Y|R|Y|R|Y|B|G|B|B|G|G|G|Lk|G|Y|Y|Bo|B|R|R|
|G|Y|R|Cr|G|Y|Bo|G|G|G|G|G|G|B|G|B|B|Y|B|B|
|G|G|R|Y|Y|Y|Y|B|Y|G|Cr|Mu|G|G|B|Y|B|B|G|R|
|G|R|R|R|G|G|Y|Y|Y|B|G|B|Y|B|Lk|Cr|Cr|R|R|Cr|
|Y|G|B|G|R|G|R|G|G|R|Lk|Y|B|Y|B|B|Mu|Y|R|B|
|R|G|B|B|B|R|Y|B|R|Lk|G|R|B|Y|G|G|Y|Y|R|Y|
|G|G|G|G|Y|G|B|Y|Mu|B|R|Y|Lk|G|Y|G|Y|R|Mu|B|
|B|G|B|Y|Y|Y|B|R|R|G|Y|B|G|G|R|R|R|G|G|Y|
|B|R|B|B|Y|G|G|B|G|R|B|Y|B|Cr|G|B|G|Y|G|G|
|G|G|Y|B|G|R|Y|Y|Y|Lk|B|Y|G|R|Lk|B|B|G|B|R|'
]

{ #category : 'as yet unclassified' }
SGRessources class >> level3 [

	<SGLevel: 3>
	^ '|Y|Cr|R|B|B|Cr|G|Y|R|Y|B|R|Y|Y|G|R|Cr|Y|G|G|
|Lk|G|B|Y|R|B|G|Y|G|B|B|G|G|Y|B|R|Y|R|Y|B|
|G|Y|G|R|B|R|R|R|R|G|R|R|Y|G|R|B|Bo|G|G|Cr|
|Bo|G|Y|Y|B|Mu|Lk|B|Y|B|G|Y|B|G|G|Y|Y|B|R|R|
|R|B|B|Y|B|B|G|B|B|R|G|R|R|R|G|R|G|Y|Y|Y|
|B|R|Y|Y|Y|Cr|R|G|R|Y|R|G|Y|Y|B|G|Y|R|G|Bo|
|B|Y|B|Cr|Y|Y|Mu|G|G|G|Y|R|B|R|B|R|Y|B|Bo|R|
|G|G|G|Lk|R|B|B|Mu|B|G|G|R|G|B|G|Cr|Bo|B|R|B|
|R|G|B|Y|Cr|B|G|Y|B|B|R|Y|Y|G|Bo|R|G|R|R|Y|
|B|R|G|B|R|G|B|G|G|B|G|Y|B|G|R|G|B|Y|Y|R|
|G|B|Y|Y|B|G|B|G|G|B|Y|Y|R|Y|R|Y|R|Y|R|B|
|B|R|B|Y|Y|Lk|Y|G|Y|Y|R|B|Cr|Y|B|B|Mu|B|Y|G|
|G|R|Y|B|B|R|Y|G|Y|R|B|Y|G|Y|G|Y|B|Y|B|Y|
|B|G|Y|B|R|Mu|Cr|Y|R|Y|R|R|Y|G|R|G|R|B|Cr|G|
|G|G|Lk|G|Y|B|B|R|Y|Bo|Y|G|Y|R|Y|B|Y|Y|B|Y|
|Y|G|Mu|Mu|B|Y|Bo|Y|B|R|B|B|G|B|R|R|Y|Y|Y|B|
|G|G|B|G|B|Lk|R|B|Cr|R|Mu|R|R|Lk|Y|R|G|G|R|Y|
|B|B|B|Mu|R|Y|Y|Lk|R|Y|G|G|Y|B|G|R|B|R|G|Bo|
|R|B|R|Y|G|R|R|G|R|B|G|Y|R|B|B|R|R|B|Y|Y|
|B|Y|Y|B|B|G|G|Lk|Y|B|Y|R|Bo|G|Y|B|G|Y|G|G|'
]

{ #category : 'as yet unclassified' }
SGRessources class >> level4 [

	<SGLevel: 4>
	^ '|R|G|Y|Mu|R|Mu|Y|G|B|B|R|Y|Y|G|R|R|G|R|G|R|
|B|G|G|G|G|B|G|Y|G|G|B|B|Y|Y|R|Lk|B|B|G|R|
|R|G|Y|Mu|B|G|R|B|Mu|Lk|Y|R|B|B|Y|G|B|G|R|Mu|
|Y|Y|Y|B|R|R|B|G|B|B|R|R|R|Y|Y|B|Y|B|B|Y|
|R|R|G|Mu|G|R|Y|R|G|G|B|Y|Y|R|G|G|R|R|R|G|
|B|B|G|Lk|Y|R|G|R|R|Lk|R|G|R|G|Y|R|B|Y|Lk|Y|
|B|Y|B|Y|G|R|G|G|Mu|Mu|Y|Mu|B|R|Bo|Y|Y|G|R|Y|
|B|Lk|Y|R|Y|G|R|G|G|Y|Y|Bo|R|G|Y|Y|Cr|R|Y|G|
|R|B|Y|R|B|R|B|Y|R|Cr|Y|G|B|G|G|G|B|Y|B|G|
|B|Lk|G|B|Bo|G|R|Y|Y|Y|B|B|B|Y|G|B|R|B|Y|Y|
|R|Lk|B|B|B|Y|B|G|R|B|R|R|Lk|B|Mu|R|G|G|B|Cr|
|R|G|Y|R|R|G|R|R|B|B|Mu|B|B|Y|R|B|Y|G|B|R|
|B|G|Y|Y|B|R|B|R|B|R|G|R|G|Cr|Mu|Y|Y|R|R|Y|
|G|Y|B|B|G|G|Y|Cr|Y|Y|B|G|Bo|G|G|G|B|R|R|R|
|Y|Y|Mu|R|Y|R|G|R|Y|G|R|R|Y|B|Y|R|G|Y|R|Bo|
|Cr|G|Bo|B|R|Y|Cr|Y|Cr|Y|G|B|R|Bo|R|R|Y|R|Y|Y|
|G|B|B|G|G|B|B|B|G|Y|Y|Mu|R|B|R|R|Y|G|R|Y|
|B|R|Y|R|R|B|B|Y|Bo|R|G|B|G|B|Y|Y|B|Y|B|B|
|R|G|R|R|Y|B|G|R|R|B|G|R|B|Lk|Y|G|Y|Y|R|Y|
|R|G|R|R|Cr|R|B|G|Y|B|R|G|Mu|Bo|Y|Y|G|Lk|R|B|'
]

{ #category : 'as yet unclassified' }
SGRessources class >> level5 [

	<SGLevel: 5>
	^ '|B|R|Y|Y|G|G|B|B|G|B|Y|Cr|Y|R|Y|Cr|R|Y|Y|B|
|R|Y|B|G|Y|G|G|Y|G|G|R|R|G|Y|B|Mu|R|B|Y|R|
|B|Y|G|B|Y|B|G|G|R|Y|R|Lk|R|B|B|G|B|B|B|R|
|R|Y|Y|Mu|G|Y|B|G|R|Cr|G|G|G|G|R|B|Y|G|B|G|
|B|Cr|R|R|B|R|Y|B|Cr|Cr|Lk|R|B|B|Lk|B|G|B|R|R|
|G|B|G|Lk|R|G|Y|Y|G|Y|G|R|B|Y|Lk|G|Y|Y|B|B|
|Y|Bo|G|Y|Y|B|G|R|Bo|G|B|G|G|G|G|G|R|Bo|G|B|
|B|Y|Y|G|B|Y|G|B|Y|R|Y|Y|Y|R|B|G|R|B|R|B|
|Y|Y|B|G|B|G|B|R|Y|B|R|Y|Y|G|G|R|R|Bo|G|B|
|R|G|Lk|B|G|B|Y|G|R|B|R|G|R|R|B|R|B|Y|G|G|
|G|Mu|Y|Y|G|Y|Y|Y|G|B|B|R|Y|R|Y|Y|Y|G|Y|Lk|
|B|Y|B|R|G|Y|Y|Y|Y|Y|R|Y|Y|Y|R|G|G|Cr|B|Y|
|Cr|Y|Y|G|Bo|R|G|Y|R|Y|R|R|R|Y|Y|Y|G|Bo|Y|Y|
|Y|G|B|G|G|G|G|G|Y|R|R|B|G|G|Y|B|R|Y|Y|G|
|R|Y|R|Y|Y|Lk|R|B|G|B|R|B|B|R|B|R|G|R|R|Y|
|R|G|Bo|R|G|G|G|G|G|Y|R|R|R|Y|R|R|Y|G|R|B|
|B|Mu|R|R|G|G|R|G|R|R|G|Y|R|Y|G|G|G|Mu|G|G|
|R|R|Y|B|Y|R|R|B|B|G|Y|Lk|G|G|Lk|R|B|B|G|B|
|Bo|Y|G|B|R|G|Y|G|Y|B|G|B|B|G|G|Y|Bo|B|B|B|
|R|Y|G|B|Lk|B|G|Y|B|B|R|R|B|B|Y|G|Cr|Y|G|Y|'
]
